### ISSUE TITLE
As a user, I want to be able to add an empty SVG and display an existing SVG from the list in it

### ISSUE THREAD

**Issue by sackboy31** [flightwatching/svg-animator#15]

**Comment by TimotheeJammot** [comment]
Given a user on the application, 
When the user clicks the button to create a new SVG,
Then an empty SVG display appears in the grid.

**Comment by TimotheeJammot** [comment]
Given a user on the application, an empty SVG and a displayed list of SVG,
When the user selects an SVG in the list,
Then the selected SVG is displayed in place of the empty SVG.
