### ISSUE TITLE
As a user, I want to be able to manage my grid configurations

### ISSUE THREAD

**Issue by sackboy31** [flightwatching/svg-animator#18]

**Comment by TimotheeJammot** [comment]
Given a user on the application,
When the user clicks on new configuration,
Then a new configuration is saved.

Given a user on the application and at least 1 configuration saved,
When the user clicks on a saved configuration,
Then the configuration is loaded.

Given a user on the application and at least 1 configuration loaded,
When the user clicks on save,
Then the configuration is updated.

Given a user on the application and at least 1 configuration loaded,
When the user clicks on delete,
Then the configuration is deleted.
