### ISSUE TITLE
As a user, I want my SVG grid to be in fullscreen and to be able to open a menu in front of the grid

### ISSUE THREAD

**Issue by sackboy31** [flightwatching/svg-animator#19]
Put the icon & the sidebar at the top right of the page. The icon should be fixed when scrolling the page.
Delete the actual top bar.

**Comment by TimotheeJammot** [comment]
Given a user on the application and the application on fullscreen,
When the user clicks on the top right menu button,
Then the menu is displayed at the right of the windows.

Given a user on the application and the menu of the application displayed,
When the user click on the top right menu button,
Then the menu is not displayed anymore.

Given a user on the application,
When the user scrolls down or up,
Then the top right menu button stays displayed.

**Comment by kladier** [comment]
Petit bug dans la feature : sur Chrome une des SVG dépasse de la sidebar (celle avec la lettre)
