### ISSUE TITLE
As a user, I want to be able to display a SVG

### ISSUE THREAD

**Issue by daohodac** [flightwatching/svg-animator#2]
The SVGs art served by a mock backend and visualized in the HTML page.

**Comment by TimotheeJammot** [comment]
Given a user on the application and a SVG file
When the user selects the option “Load a file”
Then the SVG drafts are displayed on the application

**Comment by daohodac** [comment]
OK, but this is temporary. 
Normally:
a SVG file served on the backend (Mock) and accessible by a restful API
Given a user on the application, the user can see the SVG in the front end
