### ISSUE TITLE
As a user, I want to be able to display several SVGs in a grid pattern, see: http://manifestwebdesign.github.io/angular-gridster/

### ISSUE THREAD

**Issue by daohodac** [flightwatching/svg-animator#3]
Ability to put a SVG in each DIV

**Comment by TimotheeJammot** [comment]
Given a user on the application and a displayed SVG file
When the user selects an available graph display option
Then the graph corresponding to the option is displayed in front of the draft

**Comment by daohodac** [comment]
Story#1: Given a user on the application, when the user wants to add a SVG to a grid, he can list the SVGs hosted by the server. The list of SVGs appears as stacked on the left of the page. The list is scrollable

Story#2: Given a user on the application, when the user picks up a SVG in the displayed list, he can drop it into a DIV of the grid so that the SVG is represented in it

Story#3: Given a user on the application and the list of SVG displayed, The user can hide the list of SVGs
