### ISSUE TITLE
As a user, I want to be able to access different views of my SVGs, configurations and connectors

### ISSUE THREAD

**Issue by kladier** [flightwatching/svg-animator#38]
Given a user on the application,
When he selects the sidebar SVG menu,
Then an interface to add new SVG is displayed on the screen.

Given a user on the application,
When he selects the sidebar configuration menu,
Then an interface to create, consult, update or delete configurations displayed on the screen.

Given a user on the application,
When he selects the sidebar connector menu,
Then an interface to create, consult, update or delete connectors is displayed on the screen.

**Comment by TimotheeJammot** [comment]
Given a user on the application,
When he selects the sidebar SVG menu,
Then an interface to add new SVG is displayed on the screen.

Given a user on the application,
When he selects the sidebar dashboard menu,
Then the dashboard interface is displayed on the screen.

Given a user on the application,
When he selects the sidebar connector menu,
Then an interface to create, consult, update or delete connectors is displayed on the screen.

**Comment by daohodac** [comment]
The interface to edit the SVG is not a priority. Connectors are and configs
too

Olivier Dao Hodac
*FlightWatching*

+33 6 76 81 54 11

The information in this e-mail is confidential. The contents may not be
disclosed or used by anyone other than the addressee. Access to this e-mail
by anyone else is  not authorised.
If you are not the intended recipient, please notify FlightWatching SAS
immediately and delete this e-mail.
FlightWatching SAS cannot accept any responsibility for the accuracy or
completeness of this e-mail as it has been sent over public networks. If
you have any concerns over the content of this message or its Accuracy or
Integrity, please contact FlightWatching SAS immediately.
